apiVersion: apps/v1
kind: Deployment
metadata:
  name: thangle-student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thangle
  template:
    metadata:
      labels:
        app: thangle
    spec:
      containers:
        - name: cont
          image: letanthang/nc_student
          ports:
            - containerPort: 9090
              name: web
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "75Mi"
              cpu: "75m"
